{% set name = "open-clip-torch" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlfoundations/open_clip/archive/v{{ version }}.tar.gz
  sha256: b7433baa146fdd526e53180ae3b668b91a62eb5a9ac34c45c6e67bbaf0375f22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.9.0
    - torchvision
    - regex
    - ftfy
    - tqdm
    - huggingface_hub
    - sentencepiece
    - protobuf ==3.20.*
    - timm
    - transformers
    - tokenizers >=0.11.1, !=0.11.3, <0.13

test:
  imports:
    - open_clip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlfoundations/open_clip
  summary: OpenCLIP
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
